### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by ryanzjohnson** [graphql/dataloader#138]
Before I started using dataloader if I didn't include an authorization header I would get the following error:
![image](https://user-images.githubusercontent.com/35502607/36918009-49d83796-1e0d-11e8-8add-ae2d4804b0c7.png)
When I switched to using dataloader I now get this error: 
![image](https://user-images.githubusercontent.com/35502607/36918099-8f3baea8-1e0d-11e8-900b-6e81aa4a430d.png)
and my server gives the following output: 
![image](https://user-images.githubusercontent.com/35502607/36918115-9e6d9ba2-1e0d-11e8-9054-8d0b7b051948.png)

How can I expose my true error to my users instead of the generic failed to fetch.

**Comment by jgcmarins** [comment]
It seems not to be a problem related to Dataloader.

**Comment by ryanzjohnson** [comment]
I know the issue with the no authorization headers found and we pass those during our actual calls. But we were doing unit tests and any call that uses a data loader doesn't return the true error. If we don't use the dataloader it returns the true error. 

The error isn't the issue, it's the lack of bubbling up of the error that is the issue

**Comment by janbiasi** [comment]
@ryanzjohnson think this issue has nothing to do with the `dataloader` package as you can look-up the stacktrace of the error.

**Comment by jgcmarins** [comment]
can we close this one?
