### ISSUE TITLE
Consider freezing the values returned by `load` and `loadMany`

### ISSUE THREAD

**Issue by jamesreggio** [graphql/dataloader#141]
It would help to catch development errors if DataLoader froze (preferably deep-froze) the results returned by `load` and `loadMany`, given that they are cached and reused within the instance.

Ideally, this would be gated on environment so that it doesn't run in production.

(Relay has [this behavior](https://github.com/facebook/relay/blob/2ba20d1f1e12fa358607d226a8205c9dd04a937d/packages/relay-runtime/store/RelayMarkSweepStore.js#L65-L73), as does [Apollo Client](https://github.com/apollographql/apollo-client/blob/d4dc034f1a74a177a9187870b96ac6d397064774/packages/apollo-client/src/core/ObservableQuery.ts#L272-L274).)

**Comment by leebyron** [comment]
This is a great behavior to use, however I'd suggest implementing it in your batch function if that's behavior that you would like to use. 

This sort of environment gating assumes things about the build environment that would not work for all users of DataLoader
