### ISSUE TITLE
Opportunity to update license information?

### ISSUE THREAD

**Issue by chtompki** [graphql/dataloader#143]
Would it be possible to relicense the entire project - under a MIT license? The Facebook BSD+Patent license prevents us from using the software in my company. Thanks for your consideration!

**Comment by bermanboris** [comment]
Looks like this package has been abandoned..

**Comment by chtompki** [comment]
Hm....bummer.

**Comment by locnguyen** [comment]
I'd like to see this changed to MIT as well. Can we make this happen very, very soon? It's blocking me and others from using this library.

**Comment by mgwidmann** [comment]
ping ....

**Comment by leebyron** [comment]
Closed by #176
