### ISSUE TITLE
What if DataLoader.load() calls aren't initiated on the same "tick"?

### ISSUE THREAD

**Issue by shtaif** [graphql/dataloader#150]
Let's take the GraphQL example (the one in the main page).

As far as I get it, an instance of DataLoader is effective only if all the calls to it are done during the same event loop tick (assuming the resolvers are all called themselves during the same tick from the library's logic).
But this seems to take for granted that the whole of the resolvers' operation would not span for more than one tick, or more specifically, it means **no async operations can precede the call to the DataLoader**. Otherwise, the calls to it will be spread across **multiple ticks** instead of a single one, losing the "coercing effect".

Note the change in `bestFriend` resolver function:

```js
var UserType = new GraphQLObjectType({
  name: 'User',
  fields: () => ({
    name: { type: GraphQLString },
    bestFriend: {
      type: UserType,
      /* OLD RESOLVER: */
      // resolve: user => userLoader.load(user.bestFriendID)
      /* MODIFIED RESOLVER: */
      resolve: async user => {
        await validateOrPatchSomething(user);
        return await userLoader.load(user.bestFriendID);
      }
    },
    friends: {
      args: {
        first: { type: GraphQLInt }
      },
      type: new GraphQLList(UserType),
      resolve: (user, { first }) => queryLoader.load([
        'SELECT toID FROM friends WHERE fromID=? LIMIT ?', user.id, first
      ]).then(rows => rows.map(row => userLoader.load(row.toID)))
    }
  })
})
```

Is what I figured correct? :)

**Comment by ljukas** [comment]
DataLoader does not lose its entire effect by the change you introduced. It might lose its main effect, being batching calls, it does however also have a cache. So if the bestFriend load function is called at different times but with the same argument as has been used before it will not call the database at all. It will instead used the cached response from an earlier call.

**Comment by zoidbergwill** [comment]
The Java client has the idea of manual dispatching, which could be a custom data loader that replaces the nextTick stuff with something like that:

https://github.com/graphql-java/java-dataloader#manual-dispatching

**Comment by leebyron** [comment]
> But this seems to take for granted that the whole of the resolvers' operation would not span for more than one tick, or more specifically, it means no async operations can precede the call to the DataLoader. Otherwise, the calls to it will be spread across multiple ticks instead of a single one, losing the "coercing effect".

Entirely correct! DataLoader batches only calls which occur in the same tick. Being aware of this is important to taking advantage of it's behavior!

Some things you can try for your specific example above is to make the preceding async behavior part of the same DataLoader so it's incorporated into batching, or make it a DataLoader itself so that it can be batched across other uses so multiple calls to this same GraphQL resolver will have cascading batching.

**Comment by forrestwilkins** [comment]
@leebyron Is there any way to use dataloaders in combination with an authorization middleware like GraphQL Shield?

In my case, I have shield rules that are making asynchronous function calls, which I believe are causing a new event loop tick. I've seen it suggested to simply move the async calls to after the dataloader batch calls in the execution order, but this doesn't make sense for authorization.

I also asked about this here: https://www.reddit.com/r/graphql/comments/1686dmf/dataloaders_graphql_shield_with_apollo_server_and/
