### ISSUE TITLE
Dataloader cache: TypeError: body used already for:

### ISSUE THREAD

**Issue by linh-le** [graphql/dataloader#151]
I'm new to dataloader (and graphql, and JavaScript altogether) and I came across this issue while calling the same query twice, happened when I tried to resolve the same promise twice. Given that dataloader.load(key) returns a promise, I'm not sure how to fix this issue. Could someone give me some insights? Thank you - I've simplifed my code so that I can post it on here.

**Problem:**
When I called the same query (getReturnObject()) twice, I got this error:
```
TypeError: body used already for: <service_end_point_deleted_for_privacy>
    at Response.consumeBody (/<graphql_server_path>/node_modules/node-fetch/lib/index.js:326:30)
    at Response.json (/<graphql_server_path>/node_modules/node-fetch/lib/index.js:250:22)
    at <file_path>
    at Array.map (<anonymous>)
    at <file_path>
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Code**
```
var DataLoader = require("dataloader");
// typeDefs and resolvers are combined to create the schema in another file
export const typeDefs = 
...

let dataLoader = new DataLoader(ids => {
  return Promise.all(
    ids.map(id => {
      return dataService.getById(id);
    })
  );
});

export const resolvers = {
  Query: {
      //... getReturnObject()
  },

  ReturnObject: {
    related_object: obj => {
      let relatedIds = obj.related_ids
      return dataLoader.loadMany(relatedIds) 
     } 
  }
};

```

**Comment by leebyron** [comment]
Seems like your problem isn't a DataLoader issue since your stack trace is showing that you're doing something fishy with node-fetch
