### ISSUE TITLE
SQL example is confusingly broken

### ISSUE THREAD

**Issue by ghost** [graphql/dataloader#162]
The outer loader creates a parameterized query by mapping over the ids and generating an array of '?' chars that are rendered into the query.  The inner loader is called with [ queries, ids ] but then the code in the inner loader completely ignores the ids, never passing them to the query or doing anything useful with them.  Even worse, it iterates over all of the incoming values, so it would first execute the query contained in the queries argument, and then it would execute the ids as a query, which would certainly fail.  

Examples that don't work are often worse than no examples at all, since they can send someone in the wrong direction rather than simply leaving them uninformed.

**Comment by leebyron** [comment]
Fixed by #139
