### ISSUE TITLE
Why array and not object as "many" return value?

### ISSUE THREAD

**Issue by tomhicks** [graphql/dataloader#167]
I've always wondered why the API requires returning a potentially sparse array instead of a map of key-value? Having to fill in the nulls seems error prone and awkward.

Would you consider a PR for opting into a map-response API via options, or is there some fundamental reason a map won't work?

**Comment by conradreuter** [comment]
You can easily build your object and then do `keys.map(k => obj[k])` at the end. Keeping the API surface small and clean is favorable over providing such small utility functions.
