### ISSUE TITLE
What is the best practice for errors separation inside a batch?

### ISSUE THREAD

**Issue by kityan** [graphql/dataloader#169]
DataLoader seems to be awesome to me, but...
For example, I have a query:
~~~~
{
  u1: user(id: 2) {
    name
  }
  u2: user(id: 21) {
    name
  }
}
~~~~
And there is **no user with id = 21** in database. **I reject a Promise** in my DB accessor function wrapped with DataLoader **if user doesn't exists**
If I don't use batching with DataLoader, **I recieve reasonable response:**
```json
{
  "errors": [
    {
      "message": "No user for id = 21",
      "locations": [
        {
          "line": 5,
          "column": 3
        }
      ],
      "path": [
        "u2"
      ]
    }
  ],
  "data": {
    "u1": {
      "name": "User 2"
    },
    "u2": null
  }
}
```
But with batching I have this:
```json
{
  "errors": [
    {
      "message": "No user for id = 21",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "u1"
      ]
    },
    {
      "message": "No user for id = 21",
      "locations": [
        {
          "line": 5,
          "column": 3
        }
      ],
      "path": [
        "u2"
      ]
    }
  ],
  "data": {
    "u1": null,
    "u2": null
  }
}
```
Which is not correct...

**Comment by kityan** [comment]
Sorry for spam, I've just found the solution in docs. Just need to return Error object for items separetly instead of rejecting Promise.

**Comment by jgcmarins** [comment]
@kityan great!
Could you please share link? Thanks!

**Comment by kityan** [comment]
@jgcmarins 
Here: https://github.com/facebook/dataloader#caching-errors
It's no as clear as it should be, imho. But it says:

> However if a batch function returns an Error instance for an individual value, that Error will be cached to avoid frequently loading the same Error.

Here is Promise.resolve call in my "fake database manager":
https://github.com/kityan/graphql-experiments/blob/e608ce1e43fb587dc6db29d6a4583dad5d379077/modules/dbManager.js#L66
dbManager.getUser is called from DataLoader with array of ids and returns Promised array.

Therefore request 
```gql
{
  u1: user(id: 1){name}
  u2: user(id: -1){name}
}
```
not fails completely but returns expected result for the first branch and null with error for the second one.

**Comment by jgcmarins** [comment]
Nice.
We've implemented a helper to do this for us: https://github.com/entria/graphql-mongoose-loader/blob/master/src/MongooseLoader.ts
And it also prepares response for a relay connection approach.

**Comment by kityan** [comment]
@jgcmarins That should be nice, because afaik DataLoader doesn't allow directly passing additional arguments to bounded db accsessing functions. So, I don't see simple way to pass context with user auth data (cookies or jwt based, e.g.)

**Comment by leebyron** [comment]
Closing since this seems answered!

Rejecting the batch promise errors all results, but returning an Error in a specific position in the resulting array errors only that one entry.
