### ISSUE TITLE
Question concerning process.nextTick

### ISSUE THREAD

**Issue by MrDesjardins** [graphql/dataloader#180]
Hello,

This is not a bug, but a question concerning the choice of `process.nextTick` versus `setImmediate`.

I see at [line 218](https://github.com/graphql/dataloader/blob/master/src/index.js#L218) the use of `process.nextTick` if the function is defined. Otherwise, to fallback to `setImmediate`. However, I believe this could be removed and directly use `setImmediate`.

From NodeJS' documentation:

> We recommend developers use setImmediate() in all cases because it's easier to reason about

and

>process.nextTick() fires immediately on the same phase
>setImmediate() fires on the following iteration or 'tick' of the event loop

I was wondering why choosing `nextTick` before `setImmediate`?

Thank you for enlighting me.

**Comment by leebyron** [comment]
I recommend reading the [description atop the enqueuePostPromiseJob](https://github.com/graphql/dataloader/blob/master/src/index.js#L201-L226)

The goal of this method is to both execute as soon as possible while also executing after any scheduled Promises. Node has a different job scheduling algorithm than the browser and `process.nextTick` plays an important role in it. Node maintains a queue of "Jobs" which execute as part of the current run-loop (or phase). The run-loop itself is the first Job, `process.nextTick` can schedule another onto the same phase. And creating a promise also schedules a special Job which collects all Promises created in the phase. By combining the two mechanisms we can schedule a Job that runs as part of the same Phase but after all Promise resolutions have been executed. `setImmediate` schedules the next phase and many other Jobs may have occurred before this. To get the best performance, we want to dispatch the DataLoader's batch function as soon as possible, and this use of `process.nextTick` over `setImmediate` lets us do that.

**Comment by forrestwilkins** [comment]
@leebyron I've found that the choice of `process.nextTick` has made it very difficult to use middleware that makes asynchronous calls to the DB or other services. Is there any way to use dataloader in combination with something like an authorization layer like GraphQL Shield? I have authorization rules that are making asynchronous calls, which prevent the dataloader from doing its job.
