### ISSUE TITLE
[Q] What's the differences between dataloader and lodash.memoize?

### ISSUE THREAD

**Issue by mrdulin** [graphql/dataloader#184]
I made a demonstration uses `lodash.memoize` to solve the `N + 1` query issue.

Here is my query case: there are 10 posts belongs to 1 user. And, the client side `GraphQL` query like this: 

```graphql
query {
  posts{
    postId
    postTitle
    postAuthor{
      userId
      userNme
      userEmail
    }
  }
}
```

If don't use `dataloader` or some memoize function, it will send  11 (10 + 1) times queries to database. 1 time query for `posts`, 10 time queries for the user of each post.

```ts
constructor() {
    super();
    this.userLoader = this.createLoader(this.findByIds.bind(this));
    this.userLoaderLodash = _.memoize(this.findByIds.bind(this));
  }

  public async findByIds(ids: string[]) {
    return this.db('users').whereIn('user_id', ids);
  }

  public async findById(id: string) {
    this.ids.push(id);
    // return new Promise((resolve, reject) => {
    // process.nextTick(() => {
    return this.userLoaderLodash(this.ids).then((users: any[]) => {
      // resolve(_.first(users));
      return _.first(users);
    });
    // });
    // }).then((user) => {
    // this.ids = [];
    // return user;
    // });

    // return this.userLoader.load(id);
  }
```

`this.userLoader` is a `dataloader`, `this.userLoaderLodash` is implementated by `lodash.memoize`.

Here is the database debug logs: 

```bash
{ method: 'raw',
  sql: '\n      SELECT * FROM posts;\n    ',
  bindings: [],
  options: {},
  __knexQueryUid: '046167c1-35d7-427f-8f3d-d4ac203670a6' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],
  __knexQueryUid: '450f19b7-3841-4c08-81f0-ca740f3abcf9',
  sql: 'select * from "users" where "user_id" in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' }
```

As you can see, the way of using `lodash.memoize` seems can solve the `N + 1` query issue too. Not using `process.nextTick` seems don't affect the results. 

So I have two things don't understand.

1 . what's the differences between `dataloader` and lodash.memoize?
2. It seems `dataloader` use `process.nextTick`, why should use `process.nextTick`?

P.S. I know the event loop of Node.js. But still, don't understand why `dataloader` use it and what issue to solve?

Let me remember a library for `React.js`, https://github.com/reduxjs/reselect 

I think they use the same concept - `memoize`

**Comment by scf4** [comment]
Dataloader will coalesce multiple requests into a single data fetching function.

The following is only one request with Dataloader, but four with your memoized fetching function:

```
userLoader.loadMany([1, 2]);
userLoader.loadMany([2, 1]);
userLoader.load(1);
userLoader.load(2);
```
