### ISSUE TITLE
[Q] How to use dataloader with SQL query contains orderBy, limit?

### ISSUE THREAD

**Issue by mrdulin** [graphql/dataloader#190]
`postgresql` SQL like this:

```sql
select * from "USER" where "organization_id" = ? order by "user_id" asc limit ?
```

Before using dataloader, the query debug logs:

```sql
{ method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 1 ],
  __knexQueryUid: '8e0a3e49-487b-4169-860d-8e74cf766cce',
  sql:
   'select * from "USER" where "organization_id" = ? order by "user_id" asc limit ?' }
{ method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 3, 1 ],
  __knexQueryUid: 'c835a7ab-7571-4d8a-9024-396e8216ed30',
  sql:
   'select * from "USER" where "organization_id" = ? order by "user_id" asc limit ?' }
{ method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 5, 1 ],
  __knexQueryUid: 'b930fda7-ac82-4402-a693-222cc20ba9b2',
  sql:
   'select * from "USER" where "organization_id" = ? order by "user_id" asc limit ?' }
{ method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 2, 1 ],
  __knexQueryUid: '9b96b673-025b-44bc-8990-e4337f8a2e41',
  sql:
   'select * from "USER" where "organization_id" = ? order by "user_id" asc limit ?' }
{ method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 85, 1 ],
  __knexQueryUid: '5d91b40c-95da-4bdf-9f9b-b22077ddc20b',
  sql:
   'select * from "USER" where "organization_id" = ? order by "user_id" asc limit ?' }
{ method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4, 1 ],
  __knexQueryUid: '90a7bed0-2ad2-483a-95ae-b92c2d974218',
  sql:
   'select * from "USER" where "organization_id" = ? order by "user_id" asc limit ?' }
{ method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 86, 1 ],
  __knexQueryUid: '3f238005-affb-43e5-a2b7-1b85550d42da',
  sql:
   'select * from "USER" where "organization_id" = ? order by "user_id" asc limit ?' }
```

I try to using `whereIn` instead of `where` and sort the result using `organization_id`. But the result returned is not correct. I think the issue caused by `orderBy` and `limit`.

```sql
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 3, 5, 2, 85, 4, 86 ],
  __knexQueryUid: '3511664e-a9f7-414f-9ea3-6410120ba17c',
  sql:
   'select * from "USER" where "organization_id" in (?, ?, ?, ?, ?, ?, ?) order by "user_id" asc' }
```

How to use dataloader handle this query?

**Comment by tuananh** [comment]
in this case, should `order by orgainization_id, user_id` fix the issue?

**Comment by ljukas** [comment]
Dataloader is a key-value store, kind of. So adding sql-query things like orderby/limit into the key will lower the cache hits you get.

If I were you I'd just do a 'select * from "USER" where "organization_id" = ?' query and then use javascript to limit and order it. If you have another loader that you use to collect Users by their Id, you can prime it with all the retrieved users from this query, which might increase your cache hits.

**Comment by mrdulin** [comment]
@ljukas Thanks. Recently, I found many aggregate queries with where clause, group by clause. I try to figure it out. One way is like you said, try to do a simple query without aggregate and do the aggregate in the application code.

But I am looking for a SQL way, try to map the recordSet to bindings.

**Comment by ljukas** [comment]
I don't think you want to use DataLoader in that case @mrdulin. It is not meant to be used that way. Say you do a query that results in you wanting to batch three of these sql queries together with dataloader, but there is a different count/limit on the three calls. It is pretty much impossible to batch that together in a single SQL-query without it becoming overly complex. The batch function that you pass into a loader always takes an array of arguments and need to resolve an array with the results with the order of the two matching. This is why you want as simple keys as possible passed into this batch function. 

If you want to do complex sql-queries like this I'd just recommend you don't use DataLoader for these queries.
