### ISSUE TITLE
How can I simulate clear cache case?

### ISSUE THREAD

**Issue by mrdulin** [graphql/dataloader#193]
After reading this: https://github.com/graphql/dataloader#clearing-cache

I understand that if I want to load data from dataloader cache, I need to make sure these load operations should be executed in the same tick.

So, here is my unit test: 

```ts
 it('should load cache data if not clear cache after a mutate', async () => {
      const id = '1';
      const user = await UserLoader.findByIds.load(id);
      expect(user).toEqual({ id: 1, name: 'ts', email: 'aaa@gmail.com' });
      const updatedUser = await User.updateById(id, { name: 'go', email: 'bbb@qq.com' });
      expect(updatedUser).toEqual({ id: 1, name: 'go', email: 'bbb@qq.com' });
      const user2 = await UserLoader.findByIds.load(id);
      expect(user2).toEqual({ id: 1, name: 'ts', email: 'aaa@gmail.com' });
      expect(user).toBe(user2);
    });
```

The test result is :

```bash
● UserLoader › #findByIds › should load cache data if not clear cache after a mutate

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Object {
    -   "email": "aaa@gmail.com",
    +   "email": "bbb@qq.com",
        "id": 1,
    -   "name": "ts",
    +   "name": "go",
      }

      58 |       expect(updatedUser).toEqual({ id: 1, name: 'go', email: 'bbb@qq.com' });
      59 |       const user2 = await UserLoader.findByIds.load(id);
    > 60 |       expect(user2).toEqual({ id: 1, name: 'ts', email: 'aaa@gmail.com' });
         |                     ^
      61 |       expect(user).toBe(user2);
      62 |     });
      63 |   });

      at Object.<anonymous> (src/dataloader/__tests__/clear-cache/index.spec.ts:60:21)
      at fulfilled (src/dataloader/__tests__/clear-cache/index.spec.ts:4:58)

  console.count src/dataloader/__tests__/clear-cache/index.spec.ts:9
    User.findByIds: 1

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        4.147s
Ran all test suites matching /\/Users\/elsa\/workspace\/github.com\/mrdulin\/apollo-graphql-tutorial\/src\/dataloader\/__tests__\/clear-cache\/index.spec.ts/i.
npm ERR! Test failed.  See above for more details.
```

There are three `async/await` statement, each of them executed in a new tick. So I think that's why the second `await UserLoader.findByIds.load(id);` try to load from the cache, but it loads the fresh data after mutating the data.

So, how can I simulate this workflow? I think maybe I should do this:

```ts
const [user1, _, user2] = await Promise.all([
  Userloader.findByIds.load(1),
  User.updateById(1, { name: 'go', email: 'bbb@qq.com' }),
  Userloader.findByIds.load(1),
])
```

This will make sure these three operations execute in the same tick.  But I can't control the execution order so that I can't control the second `Userloader.findByIds.load(id)` load from the cache after a muation.

Expect second `Userloader.findByIds.load(id)` load old data from the dataloader cache, because I don't clear the old data from the cache after a mutation. If I can't reproduce this case, I have no confidence to use clear cache.

**Comment by leebyron** [comment]
Seems like you may have a bug where `User.updateById` is mutating data you're already returned. DataLoader will cache the result, but if that cached result is mutated, you're going to see that mutation everywhere.
