### ISSUE TITLE
Can not pass arguments into batch function

### ISSUE THREAD

**Issue by bssergy** [graphql/dataloader#196]
I have the next query:
```
users {
  products(isDeleted: false, categoryId: 23) {
    name
    price
  }
}
```
I have property resolver:
```
productsLoader = new DataLoader(keys => this.productsService.load(keys));
async products(@Parent() user, @Args() args) {
  // what about args here???
  this.productsLoader.load(user.id);
}
```
How should I pass args into productsService.load() method in a correct way?

**Comment by nick-keller** [comment]
@bssergy checkout the `cacheKeyFn ` in the [documentation](https://github.com/graphql/dataloader#api) and do `this.productsLoader.load({ id: user.id, param1 : 'value1', param2: 'value2'... })`

**Comment by leebyron** [comment]
DataLoader assumes a strict Key -> Value association. If more than just an identifier is necessary, then "Key" needs to represent all relevant information to fetch a value.
