### ISSUE TITLE
 How to check that the dataloader is getting destroyed at the end of graphql query? 

### ISSUE THREAD

**Issue by mahaben** [graphql/dataloader#200]
Hi there,

I'm facing an issue using dataloader with graphql. Memory keeps increasing while handling requests and never getting released. 

Any help would be appreciated.

**Comment by bl1mp** [comment]
is that a problem with cache? sounds like it

**Comment by leebyron** [comment]
I'd suggest doing some googling for Node memory debugging. There are some great tools and techniques for analyzing memory dumps and figuring out what's going on. Perhaps you've created a circular reference memory leak, are reusing caches in a dangerous way, or it could be a myriad of other potential memory issues. Long-running Node programs are hard!
