### ISSUE TITLE
Directly interact with cache

### ISSUE THREAD

**Issue by nhanquach** [graphql/dataloader#211]
Hi everyone,
I'm running in a situation that I need to send some data to a storage service and then use the `load()` to retrieve the data from the storage service.
Is there any way I can cache and then later update  this data without using `load()`?

Thank you.

**Comment by jjangga0214** [comment]
@nhanquach What do you mean more specifically? You can use `prime` to create/update cache without actually fetching data from data source.

**Comment by nhanquach** [comment]
> 
> 
> @nhanquach What do you mean more specifically? You can use `prime` to create/update cache without actually fetching data from data source. This pattern is generally used when there are many dataloaders which loads same type of data with different keys, so that they "push" cache each other to reduce duplicate data fetch.

Thank you so much, this is exactly what I'm looking for.
