### ISSUE TITLE
[QUESTION] Knex example unnecessary .then

### ISSUE THREAD

**Issue by nickharder88** [graphql/dataloader#230]
Below is the example for using knex. What benefit does the .then provide? 

`
user: new DataLoader(ids => db.table('users')
    .whereIn('id', ids).select()
    .then(rows => ids.map(id => rows.find(x => x.id === id)))),
`
Isn't it "doing nothing", in the sense that the map will return the same value?

**Comment by nickharder88** [comment]
Perhaps its related to this

> There are a few constraints this function must uphold:

    The Array of values must be the same length as the Array of keys.
    Each index in the Array of values must correspond to the same index in the Array of keys.

**Comment by tuananh** [comment]
well because knex may return less items than the input `ids` (id not exists in database) ; in this case, we need to map `ids` to map and fill in the blank value.

**Comment by nickharder88** [comment]
That makes sense, it also just clicked that this is a way, give [2, 1, 2] to make sure we return the values in the same order as requested so that knex's return value of [obj1, obj2] could map to [obj2, obj1, obj2]. Thanks!

**Comment by koistya** [comment]
@nickharder88 most likely you would just need to enhance this mapping logic a little to make it more efficient and less verbose:

```js
import { mapTo } from '../utils';

const storyById = new DataLoader(keys =>
  db
    .table('stories')
    .whereIn('id', keys)
    .select()
    .then(mapTo(keys, x => x.id)),
);
```

https://github.com/kriasoft/react-firebase-starter/blob/6946f2fec656279a19e1e5631b4b89d0e7229dee/src/server/context.js#L72-L175

https://github.com/kriasoft/react-firebase-starter/blob/master/src/server/utils/map.js
