### ISSUE TITLE
[QUESTION] "Using with GraphQL" readme - queryLoader function

### ISSUE THREAD

**Issue by gffuentes** [graphql/dataloader#234]
In the README under the "Using with GraphQL" section, you use a `queryLoader` function that is not defined anywhere. I am having trouble understanding how this function is created with DataLoader since DataLoader expects the same number of objects out as it takes in and the output of `queryLoader` (in this case 5 friends) _should_ be greater than the number of keys in - 1.

In the case that queryLoader was not created with DataLoader, it would be great to get a full graphql example in the readme or in the examples repo

**Comment by MattGson** [comment]
Data loader 'expects the same number of objects out as it takes in'  - correct.
With query loader, the output is an array object. One array for each input key.

So if you are parallel loading the friends for many users (across multiple parallel resolve trees in GQL for example) then data loader can batch these. 

However, I personally think the query loader example is ambiguous and doesn't really demonstrate how one could effectively execute this with a RDBMS.

Instead I would create a friendLoader that takes user ids and returns lists of friends user ids so for example:
```
user ids in -> friend ids for each user out
[1, 4, 5] -> [ [3, 4], [1, 2], [6] ]
```


Note that the length of the input and output array is the same but the length of the friend arrays does not have to be the same.

in SQL you could query:
```
SELECT id, friend_id FROM friends WHERE id IN (keys)
```
Where keys is the input user ids to the loader.
You then need to group the resulting rows back to the input keys.
An example using lodash:

```
const grouped = _.groupBy(rows, 'id');
return keys.map(id => grouped[id] || []);
```
Note I use `|| []` to add an empty list in the case no rows were returned for a key.

so a full example looks like:

```
const friendLoader = new DataLoader(ids => {
        const rows = await query("SELECT id, friend_id FROM friends WHERE id IN (?)", ids);
        const grouped = _.groupBy(rows, 'id');
        return ids.map(id => grouped[id] || []);
    })
```

**Comment by gffuentes** [comment]
Thanks for the help! If you are open to it, i can open a PR adding your example and a better explanation to the README?
