### ISSUE TITLE
[BUG] 'ReferenceError: setImmediate is not defined' on the browser

### ISSUE THREAD

**Issue by asyncmax** [graphql/dataloader#249]
## Expected Behavior

DataLoader should gracefully fall back to `setTimeout` if `setImmediate` is not supported on the browser.

## Current Behavior

It crashes with an error `ReferenceError: setImmediate is not defined`.

## Possible Solution

https://github.com/graphql/dataloader/blob/249b2b966a8807c50e07746ff04acb8c48fa4357/src/index.js#L242
```diff
-    setImmediate || setTimeout;
+   typeof setImmediate === 'function' ?
+      setImmediate :
+      (fn => {setTimeout(fn, 0);});
```
This code also fixes a problem of calling `setTimeout` without a delay number when it falls back.
Sorry, I didn't create a PR as I am not familiar with the Flow typing that this project is based on.

**Comment by Discordius** [comment]
This appears to also be breaking my build.

**Comment by DoneDeal0** [comment]
@Discordius , @asyncmax : you need to remove setImmediate() in index.js, it works afterwards. Since the repo doesn't seem to be actively maintained anymore, I won't send a PR, but you you can fork the project and add it to your codebase.

**Comment by DoneDeal0** [comment]
Adding Yuzu's polyfill fixed the issue for me: https://github.com/YuzuJS/setImmediate/blob/master/setImmediate.js

On top of index.ts/js or at the top of your file(s) that use dataloader, just add:
```js
import "setimmediate";
```

**Comment by nanto** [comment]
Since `setImmediate` is no longer on a standard track and latest major browsers don't implement it (IE 11 is no longer a "major browser"), I think it is better if we can run `dataloader` on browsers without `setImmediate` polyfill.

**Comment by saihaj** [comment]
#293
