### ISSUE TITLE
Can dataLoader.load() accept non-scalar values?

### ISSUE THREAD

**Issue by otang** [graphql/dataloader#253]
Is it acceptable to pass non-scalar values to a dataloader's load() method? For example, passing in an object with 2 properties if our loader method is querying for data based on multiple columns?

Thank you.

**Comment by cYee992** [comment]
Yes, you can load with non-scalar value. Pass in `cacheKeyFn` into your object.
In case, for two object props, you can append the two key together to form as one. 
eg: 
`cacheKeyFn : (myObj) => return `${myObj.firstProp}${myObj.SecondProp}``
https://github.com/graphql/dataloader#new-dataloaderbatchloadfn--options

**Comment by otang** [comment]
Thank you, @cYee992
