### ISSUE TITLE
Setup Renovate Bot to keep dependencies up to date

### ISSUE THREAD

**Issue by saihaj** [graphql/dataloader#305]

**Comment by saihaj** [comment]
Hey @brianwarner can you please add https://github.com/marketplace/renovate to this repo? thanks!

**Comment by brianwarner** [comment]
Thanks @saihaj, I've filed a ticket at https://support.linuxfoundation.org/ (LFX Support -> EasyCLA, in case you need it and I'm not around).

**Comment by brianwarner** [comment]
This should be done now.
