### ISSUE TITLE
[QUESTION] README.md doesn't show on npmjs.com

### ISSUE THREAD

**Issue by trevor-scheer** [graphql/dataloader#317]
The README doesn't show on npm for some reason:
https://www.npmjs.com/package/dataloader

Confirmed the README is correctly published, so I'm not sure why this is the case.
https://unpkg.com/dataloader@2.1.0/README.md

**Comment by saihaj** [comment]
I do see it 
![6A829317-43EA-49FB-BAD5-E722BB40FB3D](https://user-images.githubusercontent.com/44710980/195457103-7a180865-bc5b-41c7-9d2b-32c91fa065b3.png)

**Comment by trevor-scheer** [comment]
Same, possibly an NPM hiccup. Thanks for taking a look 👍
