### ISSUE TITLE
[QUESTION] Release changes?

### ISSUE THREAD

**Issue by henrinormak** [graphql/dataloader#328]
I couldn't find anything on this, but what is the plan with unreleased changes? Currently seems the latest release was in April '21, since then quite a few changes have been merged, but have not been released.

Looking forward to a release, especially for the name feature merged in #326

**Comment by SimenB** [comment]
The release action seems to have permission errors: https://github.com/graphql/dataloader/actions/runs/3981356634/jobs/6825040158

**Comment by henrinormak** [comment]
Did not realise this was even set up for this repository, do you happen to know who could fix this and get the ball moving? The package is heavily used 3+M weekly downloads, yet no release for more than a year...

**Comment by SimenB** [comment]
@saihaj maybe?

**Comment by saihaj** [comment]
sorry everyone I was out last week but will try to get something running now that I have access to publish

**Comment by saihaj** [comment]
@thekevinbrown so looping in you here too for update. So running tests locally I see I may have merged a PR that broke some Flow types. I suspect it is this commit https://github.com/graphql/dataloader/commit/588a8b6c6391aad042b369f10dc440c7e0458312 so trying to see what needs to be fixed (I am not a Flow expert)

**Comment by SimenB** [comment]
Sent: https://github.com/graphql/dataloader/pull/330

**Comment by saihaj** [comment]
https://github.com/graphql/dataloader/releases/tag/v2.2.0

**Comment by saihaj** [comment]
I think I may have actually fixed the CI release flow https://github.com/graphql/dataloader/commit/dfb9d93e76d89e2ae1df2fbdf6345198df3220dc or maybe it is just me who pushed directly that worked. Very unclear to me cause the errors I saw on CI were related to GH Token. I guess we will figure out if the CI actually works in future release.
