### ISSUE TITLE
[BUG] Readme is missing from NPM

### ISSUE THREAD

**Issue by thekevinbrown** [graphql/dataloader#333]
## Expected Behavior
Contents of Readme.md should be visible [on the NPM package](https://www.npmjs.com/package/dataloader) so that users can tell what the package does. In addition this content is indexed by NPM to help users searching for packages to locate the package.

## Current Behavior
Readme contents are not displayed on the NPM package here: https://www.npmjs.com/package/dataloader

## Possible Solution
Ensure that Readme.md is published in the root of the package.

## Steps to Reproduce
Visit https://www.npmjs.com/package/dataloader

## Context
Most other packages show readmes on NPM, for example:
 - [Express](https://www.npmjs.com/package/express)
 - [React](https://www.npmjs.com/package/react)

**Comment by Timeraa** [comment]
Readme is actually visible for me on NPM, I had these issues before as well but I think it was a general NPM bug.

**Comment by saihaj** [comment]
seems like some NPM issue visiting the page it seems to be there.
![CleanShot 2023-02-08 at 16 57 12](https://user-images.githubusercontent.com/44710980/217660390-5f046877-3dea-4dc4-bb6e-317759789778.png)
