### ISSUE TITLE
Coalescing multiple load() calls

### ISSUE THREAD

**Issue by ovaris** [graphql/dataloader#349]
I'd like to use Dataloader with await's, but the problem is that batching doesn't work, I guess it has something to do with ticks & event loop. Could someone give me a working example where I could use await's to call load() functions so that it would still use batching?

A simple test.js script:
```javascript
const DataLoader = require('dataloader')

const testLoader = new DataLoader((ids) => {
  console.log('testLoader', ids)
  return Promise.resolve(ids)
})

const dummyFunction = async () => {
  await testLoader.load(1) // <--- DOES NOT BATCH
  await testLoader.load(2)

  await Promise.all([testLoader.load(3), testLoader.load(4)]) // <-- BATCHES
}

;(async () => {
  await dummyFunction()
})()
```

output:
```
node --version
v16.20.2
node test.js
testLoader [ 1 ]
testLoader [ 2 ]
testLoader [ 3, 4 ]
```

I have a async Express handler function where I'd like to use loader with await's to load stuff from DB, so really basic stuff.
Any tips appreciated!

**Comment by joewestcott** [comment]
If you use the `await` keyword, execution will pause at that step until completion, hence, no batching.

**Comment by ovaris** [comment]
Yeah, thanks, makes perfectly sense, closing this issue.
