### ISSUE TITLE
[REQUEST] Can you please release the latest changes? 🙏 

### ISSUE THREAD

**Issue by btabram** [graphql/dataloader#366]
The release action has failed on the last three merges to main. It looks like it might be a permissions issue with this repo not allowing pull requests to be created by actions? Not a code problem from what I can tell

## What problem are you trying to solve?

I'm particularly interested in https://github.com/graphql/dataloader/pull/342 which looks like a great change. We recently got caught out when we set a default `cacheKeyFn` for our loaders and had been assuming that it would never be called when `cache: false` was provided (my bad, I checked the source code here but didn't notice it was an unreleased change).

## Describe the solution you'd like

Release a new version of the package which includes https://github.com/graphql/dataloader/pull/342

**Comment by jekanik** [comment]
Supporting this issue :) 
@saihaj could you pls take a look?

**Comment by saihaj** [comment]
hey sorry for the delays. Just published the release https://github.com/graphql/dataloader/releases/tag/v2.2.3

**Comment by btabram** [comment]
Thank you!
